# Deployment configuration

repo-name    = "SOAR-detect-log-buckets"
part-of      = 'soar'


[[pre-SAM-CloudFormation]]
name         = "INFRA-log-archive-buckets"
template     = 'cloudformation/log-archive-buckets.yaml'
account      = '{log-archive-account}'
regions      = '{main-region}'

[[pre-SAM-CloudFormation]]
name         = "INFRA-s3-log-replication-source-account-role"
template     = 'cloudformation/s3-log-replication-source-account-role.yaml'
account      = 'ALL'
regions      = '{main-region}'
capabilities = 'CAPABILITY_NAMED_IAM'

[[pre-SAM-CloudFormation]]
name         = "INFRA-detect-bucket-lifecycle"
template     = 'cloudformation/detect-bucket-lifecycle.yaml'
account      = 'ALL'
regions      = '{all-regions}'


[SAM]
stack-name   = "INFRA-detect-log-buckets"
profile      = "admin-account"
regions      = '{all-regions}'



